version: 2

defaults: &defaults
    working_directory: ~/build
    docker:
        - image: circleci/node:14

jobs:
  init:
    <<: *defaults
    steps:
      - checkout
      - run: npm ci
      - save_cache:
          key: npm-deps-{{ checksum 'package-lock.json' }}
          paths:
            - node_modules

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: npm-deps-{{ checksum 'package-lock.json' }}
      - run: npm run lint
      - run: npm run test

  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: npm-deps-{{ checksum 'package-lock.json' }}
      - run: npm run build

workflows:
    version: 2
    development:
      jobs:
        - init:
          filters:
            branches:
              ignore: master
        - test:
            requires:
              - test
            filters:
              branches:
                ignore: master
        - build:
            requires:
              - test
            filters:
              branches:
                ignore: master
